version: '3.9'
services: 
    projeto-global-postgresql:
      image: postgres:13.2
      container_name: projeto-global-postgresql
      environment: 
        POSTGRES_DB: projetoglobal
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1234@Mudar
      ports:
        - 5432:5432
      expose: 
        - 5432
      volumes: 
        - projetoglobal_postgresql_data:/var/lib/postgresql/data
    projeto-global-pgadmin:
      image: dpage/pgadmin4:5.2
      container_name: projeto-global-pgadmin
      environment: 
        PGADMIN_DEFAULT_EMAIL: root@root.com
        PGADMIN_DEFAULT_PASSWORD: root
        PGADMIN_SERVER_JSON_FILE: /custom/servers.json
        MASTER_PASSWORD_REQUIRED: 'False'
      ports:
        - 10002:80
      expose: 
        - 10002
      volumes: 
        - ./etc:/custom
        - projetoglobal_pgadmin_data:/var/lib/pgadmin
      depends_on: 
        - projeto-global-postgresql

volumes: 
  projetoglobal_postgresql_data:
  projetoglobal_pgadmin_data:
